# Manual tema 2
***Kevin Holguin***

### NumPy
NumPy es una librería diseñada para el cálculo científico y las operaciones
matemáticas con estructuras de datos matriciales. Guarda algunas semejanzas con
software de parecidos propósitos como MATLAB.

Lo primero vamos a revisar la versión de la librería que tenemos instalada.

In [2]:
import numpy as np
print('numpy version: ', np.__version__)

numpy version:  1.18.1


NumPy es una librería diseñada para trabajar con vectores multidimensionales.
as
dimensiones de la estructura de datos reciben el nombre de “axes”. Funciones útiles
para probar esta librería son:
* ▸ ndarray.ndim – número de dimensiones de la estructura vectorial.
* ▸ ndarray.shape – muestra las dimensiones del vector.
* ▸ ndarray.size – devuelve el número total de elementos.
* ▸ ndarray.dtype – devuelve el tipo de los valores contenidos en el vector.
* ▸ ndarray.itemsize – devuelve el tamaño en bytes de los elementos del vector
teniendo en cuenta su tipo.

In [16]:
#numeros complejos
b = np.array([[2,3],[6,7]], dtype = np.complex64)
print(b)

[[2.+0.j 3.+0.j]
 [6.+0.j 7.+0.j]]


### Funciones de Arrays
***La función zeros crea una matriz llena de ceros***

In [92]:
#En ocasiones es de especial utilidad inicializar vectores de unas dimensiones
#concretas a un valor que puede ser una constante como 0 o 1, o números aleatorios.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
b = np.array([[2,3],[6,7]], dtype = np.complex64)
np.zeros_like(b)

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex64)

In [29]:
np.empty((2,3))

array([[4.67506816e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#np.arange()
#es una función habitual para crear secuencias numéricas.
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
#reshape() es
#útil para ajustar las dimensiones de la estructura.
x = np.arange(4).reshape(2,2)
print(x)

[[0 1]
 [2 3]]


In [37]:
#No es necesario especificar los valores del vector uno a uno, también es posible
#recurrir a generadores como el siguiente.
c = np.array([[10*j+i for i in range(3)]for j in range(4)])
print(c)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [38]:
#Para añadir una nueva dimensión o convertir un vector fila en columna, utilizamos
#las siguientes funciones:
#Genera 5 puntos equiespasiados entre 0 y 12
d = np.linspace(0,12,5)
print(d)
print(d[:, np.newaxis])

[ 0.  3.  6.  9. 12.]
[[ 0.]
 [ 3.]
 [ 6.]
 [ 9.]
 [12.]]


In [46]:
# similar a meshgrid en Matlab
Z, Y = np.mgrid[0:5,0:5]
print(Z)
print("-----")
print(Y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
-----
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Matrices Dispersas

Se puede crear y manipular matrices dispersas de la siguiente manera:

In [47]:
from scipy import sparse
X = np.random.random((5,6)) #crea una matriz con muchos ceros
X[X < 0.85] = 0
print(X)
X_csr = sparse.csr_matrix(X) #convierte X en una matriz csr(Compressed-sparce-row)
print(X_csr)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.98557964]
 [0.         0.         0.         0.         0.93114139 0.        ]
 [0.99709853 0.         0.         0.         0.         0.        ]]
  (2, 5)	0.985579637401516
  (3, 4)	0.9311413920149639
  (4, 0)	0.9970985310592616


In [44]:
print(X_csr.toarray()) #convertir de nuevo a una matriz densa

[[0.         0.92421246 0.         0.         0.         0.        ]
 [0.         0.93941789 0.96599917 0.         0.         0.        ]
 [0.         0.         0.88779139 0.         0.8638567  0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.91705899 0.         0.         0.96360591]]


 Ademas de csr--Hay varios otros formatos dispersos que pueden ser útiles para varios problemas:
* CSC (columna dispersa comprimida)
* BSR (fila dispersa de bloque)
* COO (coordinar)
* DIA (diagonal)
* DOK (diccionario de claves)


### Numeros aleatorios

In [48]:
np.random.seed(12345) # para resultados reproducibles
np.random.rand(4,5) # numeros aleatorios uniformes en 0,1

array([[0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503],
       [0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987],
       [0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371],
       [0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535]])

In [50]:
# Devuelva una muestra (o muestras) de la distribución "normal estándar".
# Se devuelve un único flotante muestreado aleatoriamente de la distribución 
#si no se proporciona ningún argumento .
np.random.randn(4,5) 

array([[-0.8607574 ,  0.56014529, -1.26593449,  0.11982712, -1.06351245],
       [ 0.33288272, -2.35941881, -0.19954296, -1.54199553, -0.97073591],
       [-1.30703025,  0.28634975,  0.37798411, -0.75388653,  0.33128565],
       [ 1.34974221,  0.06987669,  0.24667411, -0.0118616 ,  1.00481159]])

### Transformaciones de tipos

En otras ocasiones, es útil realizar ciertas transformaciones de tipos, pasar de decimal
en coma flotante a entero, de entero a carácter, etc. También podemos necesitar
redondear un número.

In [54]:
a = np.array([1.7,1.2,1.6])
b= a.astype(int) #convierte'redondea?' a integer
b


array([1, 1, 1])

#### Redondeando

In [59]:
a = np.array([1.7,1.2,1.6,2.5,3.5,4.5])
b = np.around(a) 
print(b)  #punto flotante
c = np.around(a).astype(int)
print(c)

[2. 1. 2. 2. 4. 4.]
[2 1 2 2 4 4]


El término «broadcasting» describe la forma en la que NumPy trata a los vectores de
diferentes dimensiones, el vector de menor dimensión es distribuido sobre el largo para conseguir
dimensiones compatibles. Esto evita la creación de copias de los datos.

In [60]:
from numpy import array
a = array([1.0,2.0,3.0])
b = array([2.0,2.0,2.0])
a*b

array([2., 4., 6.])

In [62]:
a = array([[0.0,0.0,0.0],
         [10.0,10.0,10.0],
         [20.0,20.0,20.0],
         [30.0,30.0,30.0]])

b = array([1.0,2.0,3.0])
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

### Álgebra lineal básica

In [63]:
#Ejemplos de algebra lineal basica
print(x.T)

[[0 2]
 [1 3]]


In [64]:
#Suma y productos varios con NumPy
print(x*5)
print(x*3)

[[ 0  5]
 [10 15]]
[[0 3]
 [6 9]]


In [66]:
print(x*x.T)
print(np.dot(x,x.T))

[[0 2]
 [2 9]]
[[ 1  3]
 [ 3 13]]


#### Determinante de una matriz cuadrada

In [69]:
#Para el cálculo del determinante y de la matriz inversa hay que acudir a la librería SciPy.
from scipy import linalg
arr = np.array([[1,2],[3,4]]) 
linalg.det(arr) #calculo del determinante

-2.0

#### Matriz inversa cuadratica

In [70]:
print(linalg.inv(arr)) #Cálculo de la matriz inversa.

[[-2.   1. ]
 [ 1.5 -0.5]]


#### Indexación de elementos individuales

In [81]:
#indexacion de datos
#indexando elementos individuales
print(a[:, 1])

[ 0. 10. 20. 30.]


#### Indexando elemenntos multiples

In [87]:
#indexando elemenntos multiples
a = np.array([[10*j+i for i in range(6)] for j in range(6)])
print(a)
print('-----------')
print(a[0,3:5])
print('-----------')
print(a[4:,4:])
print('-----------')
print(a[:,2])
print('-----------')
print(a[2::2, ::2])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
-----------
[3 4]
-----------
[[44 45]
 [54 55]]
-----------
[ 2 12 22 32 42 52]
-----------
[[20 22 24]
 [40 42 44]]


In [90]:
#A la hora de copiar una matriz con todos sus atributos, se puede ejecutar la siguiente instrucción:
c= np.array(a, copy=True) #copia de una matriz
print(c)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

# Pandas

Para utilizar pandas importamos de la siguiente manera

In [5]:
import numpy as np
import pandas as pd

## Creando Objetos
#### Series
Al pasar una lista de valores, permitiendo que los pandas creen un índice entero predeterminado:

In [7]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


### DataFrame
Crea una matriz NumPy, con un índice de fecha y hora y columnas etiquetadas:

In [11]:
dates = pd.date_range('20130101', periods=6)
print(dates)
print("-------------------------------------------------------")
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
-------------------------------------------------------
                   A         B         C         D
2013-01-01 -0.072644  0.334069  0.736941 -1.374144
2013-01-02 -0.252327  0.865675  0.361770  0.317103
2013-01-03  0.111287 -0.205037 -0.922280  1.512381
2013-01-04  0.472831  1.004394 -0.551231 -0.010507
2013-01-05  0.499613  0.751439 -0.373139 -0.340261
2013-01-06  0.339551  0.011978 -0.167880 -0.025228


### Ver datos

Para ver un objeto de Series o DataFrame, se usa los métodos head()y tail().
<br>Se puede mostrar un número predeterminado de elementos, o se puede pasar un número personalizado.

In [13]:
df.head()

A         B         C         D
2013-01-01 -0.072644  0.334069  0.736941 -1.374144
2013-01-02 -0.252327  0.865675  0.361770  0.317103
2013-01-03  0.111287 -0.205037 -0.922280  1.512381
2013-01-04  0.472831  1.004394 -0.551231 -0.010507
2013-01-05  0.499613  0.751439 -0.373139 -0.340261

In [14]:
df.tail(3)

A         B         C         D
2013-01-04  0.472831  1.004394 -0.551231 -0.010507
2013-01-05  0.499613  0.751439 -0.373139 -0.340261
2013-01-06  0.339551  0.011978 -0.167880 -0.025228

Mostrar el índice, columnas:

In [15]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

### DataFrame.to_numpy()
Da una representación NumPy de los datos subyacentes. Tenga en cuenta que esta puede ser una operación costosa cuando DataFrametiene columnas con diferentes tipos de datos

In [16]:
df.to_numpy()

array([[-0.07264359,  0.33406906,  0.73694126, -1.37414374],
       [-0.25232749,  0.86567533,  0.3617704 ,  0.31710258],
       [ 0.11128749, -0.20503735, -0.92228002,  1.51238074],
       [ 0.47283131,  1.00439422, -0.55123071, -0.01050704],
       [ 0.49961271,  0.7514389 , -0.37313929, -0.34026149],
       [ 0.33955132,  0.01197821, -0.16787982, -0.02522754]])

### describe()
muestra un resumen estadístico rápido de sus datos:

In [17]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.183052  0.460420 -0.152636  0.013224
std    0.306190  0.490862  0.609269  0.937187
min   -0.252327 -0.205037 -0.922280 -1.374144
25%   -0.026661  0.092501 -0.506708 -0.261503
50%    0.225419  0.542754 -0.270510 -0.017867
75%    0.439511  0.837116  0.229358  0.235200
max    0.499613  1.004394  0.736941  1.512381

Transposicion sus datos:

In [18]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.072644   -0.252327    0.111287    0.472831    0.499613    0.339551
B    0.334069    0.865675   -0.205037    1.004394    0.751439    0.011978
C    0.736941    0.361770   -0.922280   -0.551231   -0.373139   -0.167880
D   -1.374144    0.317103    1.512381   -0.010507   -0.340261   -0.025228

Ordenar por un eje:

In [21]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01 -1.374144  0.736941  0.334069 -0.072644
2013-01-02  0.317103  0.361770  0.865675 -0.252327
2013-01-03  1.512381 -0.922280 -0.205037  0.111287
2013-01-04 -0.010507 -0.551231  1.004394  0.472831
2013-01-05 -0.340261 -0.373139  0.751439  0.499613
2013-01-06 -0.025228 -0.167880  0.011978  0.339551

Ordenar por valores:

In [23]:
df.sort_values(by='A')

A         B         C         D
2013-01-02 -0.252327  0.865675  0.361770  0.317103
2013-01-01 -0.072644  0.334069  0.736941 -1.374144
2013-01-03  0.111287 -0.205037 -0.922280  1.512381
2013-01-06  0.339551  0.011978 -0.167880 -0.025228
2013-01-04  0.472831  1.004394 -0.551231 -0.010507
2013-01-05  0.499613  0.751439 -0.373139 -0.340261

## Selección

### Obteniendo 
Seleccionar una sola columna, que produce un __Series__ equivalente a df.A:

In [24]:
df['A']  

2013-01-01   -0.072644
2013-01-02   -0.252327
2013-01-03    0.111287
2013-01-04    0.472831
2013-01-05    0.499613
2013-01-06    0.339551
Freq: D, Name: A, dtype: float64

## Selección por etiqueta 

Para obtener una sección transversal con una etiqueta:

In [25]:
df.loc[dates[0]]

A   -0.072644
B    0.334069
C    0.736941
D   -1.374144
Name: 2013-01-01 00:00:00, dtype: float64

Selección en un eje múltiple por etiqueta:

In [26]:
df.loc[:, ['A', 'B']]

A         B
2013-01-01 -0.072644  0.334069
2013-01-02 -0.252327  0.865675
2013-01-03  0.111287 -0.205037
2013-01-04  0.472831  1.004394
2013-01-05  0.499613  0.751439
2013-01-06  0.339551  0.011978

Para obtener un valor escalar:

In [28]:
df.loc[dates[0], 'A']

-0.07264358912047374

## Selección por posición 

Seleccione a través de la posición de los enteros:

In [29]:
df.iloc[3]

A    0.472831
B    1.004394
C   -0.551231
D   -0.010507
Name: 2013-01-04 00:00:00, dtype: float64

Por listas de ubicaciones de posiciones enteras:

In [30]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02 -0.252327  0.361770
2013-01-03  0.111287 -0.922280
2013-01-05  0.499613 -0.373139

Para cortar filas:

In [31]:
df.iloc[1:3, :]

A         B        C         D
2013-01-02 -0.252327  0.865675  0.36177  0.317103
2013-01-03  0.111287 -0.205037 -0.92228  1.512381

Para cortar columnas:

In [32]:
df.iloc[:, 1:3]

B         C
2013-01-01  0.334069  0.736941
2013-01-02  0.865675  0.361770
2013-01-03 -0.205037 -0.922280
2013-01-04  1.004394 -0.551231
2013-01-05  0.751439 -0.373139
2013-01-06  0.011978 -0.167880

Si queremos realizar una selección a través del índice deberemos emplear la función
__.loc()__

In [33]:
df.loc[dates[0]]

A   -0.072644
B    0.334069
C    0.736941
D   -1.374144
Name: 2013-01-01 00:00:00, dtype: float64

__iloc()__ es otra de las opciones posibles, observar cómo en este caso es preciso pasar
un número entero asociado a la posición del índice.

In [34]:
df.iloc[3]

A    0.472831
B    1.004394
C   -0.551231
D   -0.010507
Name: 2013-01-04 00:00:00, dtype: float64

También tenemos la opción de filtrar y seleccionar únicamente los valores que
cumplan una determinada condición.

In [35]:
df[df.A >0]

A         B         C         D
2013-01-03  0.111287 -0.205037 -0.922280  1.512381
2013-01-04  0.472831  1.004394 -0.551231 -0.010507
2013-01-05  0.499613  0.751439 -0.373139 -0.340261
2013-01-06  0.339551  0.011978 -0.167880 -0.025228

Para unir dos DataFrames, Pandas nos proporciona la
función __join()__ para este propósito.

In [38]:
a = pd.DataFrame({'key': ['foo','foo'], 'lval':[1,2]})
b = pd.DataFrame({'key': ['foo','foo'], 'rval':[4,5]})
print(a)

   key  lval
0  foo     1
1  foo     2


In [39]:
print(b)

   key  rval
0  foo     4
1  foo     5


In [40]:
pd.merge(a,b, on='key')

key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

Y también tenemos la posibilidad de ejecutar funciones de agrupación al estilo de
SQL

In [43]:
df2 = pd.DataFrame({'A': ['foo','bar','foo','bar','foo','bar','foo','foo'],
                        'B': ['uno','uno','dos','tres','dos','dos','one','tres'],
                        'C': np.random.randn(8),
                        'D': np.random.randn(8)})
print(df2)

     A     B         C         D
0  foo   uno  0.003036  0.115385
1  bar   uno  0.048813 -1.051743
2  foo   dos  0.170077  0.092851
3  bar  tres  0.006223  0.110929
4  foo   dos  0.762278 -1.857076
5  bar   dos -0.336037  0.711064
6  foo   one -0.396800 -0.117357
7  foo  tres -1.526402  0.515740


Agrupamos y luego aplicamos una suma de funciones a los grupos resultantes

In [44]:
df2.groupby('A').sum()

C         D
A                      
bar -0.281001 -0.229750
foo -0.987811 -1.250456